# Extract the `description` field from a SKILL.md YAML frontmatter block.
# Handles both an inline value and a folded/literal block scalar (`>`, `>-`,
# `|`, ...), collapsing it to a single-line string. Internal helper.
.skill_description <- function(skill_md) {
    lines <- readLines(skill_md, warn = FALSE)
    idx <- grep("^description:", lines)
    if (length(idx) == 0) return("(no description)")
    idx <- idx[1]
    val <- sub("^description:[ \t]*", "", lines[idx])
    if (grepl("^[>|]", val) || !nzchar(trimws(val))) {
        # Block scalar: collect following indented (or blank) lines until the
        # next top-level key or the closing `---`.
        parts <- character(0)
        j <- idx + 1
        while (j <= length(lines) &&
               !grepl("^---", lines[j]) &&
               (grepl("^[ \t]", lines[j]) || !nzchar(lines[j]))) {
            if (nzchar(trimws(lines[j]))) parts <- c(parts, trimws(lines[j]))
            j <- j + 1
        }
        val <- paste(parts, collapse = " ")
    }
    trimws(val)
}

# Marker comments delimiting the package-managed block inside the user's
# `AGENTS.md`. Everything between them is rewritten on each run; everything
# outside belongs to the user.
.shim_begin <- "<!-- mizerAgents: start — managed by setup_mizer_agent(), edits are overwritten -->"
.shim_end   <- "<!-- mizerAgents: end -->"

# The block itself is prose plus an `@` import because the two reach different
# agents: Claude Code and Gemini CLI resolve `@` and inline the reference card
# unconditionally at startup, while Codex and Copilot do not, so for them the
# sentence is the only thing that gets the file read. Keep this short —
# substantive guidance belongs in `inst/AGENTS.md`, which is the file agents
# read as a reference.
.shim_note <- c(
    "This project uses [mizer](https://sizespectrum.org/mizer/) for size-spectrum",
    "modelling. Read `MIZER-AGENTS.md` before writing or changing mizer code — it is",
    "imported below if your tool resolves `@` imports. It is generated by",
    "`mizerAgents::setup_mizer_agent()`; don't edit it by hand.",
    "",
    "@MIZER-AGENTS.md"
)

# Locate the package-managed block in an existing `AGENTS.md`, returning the
# line range to replace or `NULL` if there is nothing to update. Handles files
# written by earlier versions, which had no markers: those are recognised by
# their bare `@MIZER-AGENTS.md` import line, optionally preceded by the
# unmarked note that 0.3.2.9000 wrote above it. Internal helper.
.shim_range <- function(lines) {
    b <- which(lines == .shim_begin)
    e <- which(lines == .shim_end)
    if (length(b) && length(e) && e[1] > b[1]) return(c(b[1], e[1]))

    at <- which(lines == "@MIZER-AGENTS.md")
    if (!length(at)) return(NULL)
    at <- at[1]
    # Absorb the unmarked note above the import, but only on an exact match, so
    # that anything the user wrote there is left alone.
    lead <- .shim_note[-length(.shim_note)]
    if (at > length(lead) &&
        identical(lines[(at - length(lead)):(at - 1)], lead)) {
        return(c(at - length(lead), at))
    }
    c(at, at)
}

#' Set up an AI agent to help with your mizer project
#'
#' Creates (or updates) a `MIZER-AGENTS.md` file in your project directory
#' containing a concise mizer reference that AI coding agents read
#' automatically on startup. The file includes the core mizer workflow,
#' key object descriptions, and the path to the full mizer API documentation
#' bundled with the package.
#'
#' It also creates (or updates) an `AGENTS.md` file with a short note and a
#' `@MIZER-AGENTS.md` import, so that agents read both the project-specific
#' instructions and the mizer reference. Agents that resolve `@` imports (Claude
#' Code, Gemini CLI) pick the reference up automatically at startup; the note
#' tells those that do not (Codex, Copilot) to read the file themselves. This
#' block is delimited by `<!-- mizerAgents: start -->` and
#' `<!-- mizerAgents: end -->` comments and is refreshed in place on every run,
#' so that improvements to it reach existing projects. Add your own project
#' notes outside those markers, where they will be left untouched.
#' It also creates `CLAUDE.md` and `GEMINI.md` shim files (each
#' containing just `@AGENTS.md`) so that agent-specific tools that look for
#' their own named file also pick up the shared context. These shims are only
#' created if the files do not already exist.
#'
#' It also installs a set of bundled Claude Code *skills* into
#' `.claude/skills/` (one sub-directory with a `SKILL.md` per skill, e.g.
#' `analyse-and-plot` and `build-multispecies-model`). Claude Code loads these
#' automatically when a task matches, giving step-by-step guidance for common
#' mizer workflows. Like `MIZER-AGENTS.md`, the skills are package-managed and
#' refreshed on every call so they stay up to date.
#'
#' So that agents other than Claude Code (which do not discover `.claude/skills/`
#' natively) can use the skills too, an index of them — each skill's name,
#' one-line description, and path — is generated from the skills' own frontmatter
#' and added to `MIZER-AGENTS.md`. Those agents can then read the relevant
#' `SKILL.md` on demand when a task matches.
#'
#' Finally, unless `r_session = FALSE`, it configures an MCP server named
#' `r-mizer` in the project's `.mcp.json`, so that the agent can reach your live
#' R session. The server is provided by the
#' [btw](https://posit-dev.github.io/btw/) package, which you need to install
#' separately. This gives the agent help pages and vignettes for the mizer
#' version you actually have installed — rather than whatever mizer API it
#' remembers — along with a view of the objects in your global environment and
#' of the document open in RStudio, and it can run mizer code there and see the
#' plots that come back. For the server to see your session you must run
#' `btw::btw_mcp_session()` in the RStudio console; passing `rprofile = TRUE`
#' adds that call to the project `.Rprofile` so that it happens automatically.
#' Only the `r-mizer` entry of `.mcp.json` is package-managed; other servers you
#' configure there are left alone.
#'
#' After running this function, start your AI coding agent
#' (e.g. `claude`, `codex`, `copilot` or `gemini`) from the RStudio Terminal
#' and it will immediately have the mizer context it needs.
#'
#' @param path Directory in which to create or update the agent files. Defaults
#'   to the current working directory, which should be your R project root.
#' @param overwrite If `TRUE`, replace an existing `AGENTS.md` entirely with a
#'   clean shim, discarding your project notes. If `FALSE` (the default), keep
#'   the rest of `AGENTS.md` and only refresh the marked mizer block, adding it
#'   at the top if it is not there yet. `MIZER-AGENTS.md` is always overwritten
#'   to ensure it stays up-to-date.
#' @param r_session If `TRUE` (the default), configure the `r-mizer` MCP server
#'   in `.mcp.json` so that the agent can read mizer's documentation, your
#'   global environment and the open RStudio document. Set to `FALSE` to leave
#'   `.mcp.json` alone.
#' @param run_r If `TRUE` (the default), let the agent *evaluate* R code in your
#'   session, which is what allows it to project or calibrate a model and see
#'   the resulting plots. The code runs in your global environment with no
#'   sandboxing, so the agent can overwrite your objects; work under version
#'   control, or set this to `FALSE` for a read-only connection. Ignored when
#'   `r_session = FALSE`.
#' @param pkg_dev If `TRUE`, also expose btw's package development tools
#'   (`load_all()`, `document()`, `test()`, `check()` and test coverage), which
#'   run against the package in your session's working directory. Set this when
#'   the project is itself an R package, such as a mizer extension. `FALSE` by
#'   default, since these tools do nothing useful in an ordinary modelling
#'   project. Ignored when `r_session = FALSE`.
#' @param rprofile If `TRUE`, append a guarded `btw::btw_mcp_session()` call to
#'   the project `.Rprofile`, so that each new session hands itself to the MCP
#'   server automatically. `FALSE` by default, in which case you call
#'   `btw::btw_mcp_session()` yourself. Ignored when `r_session = FALSE`.
#'
#' @return Invisibly returns the path to the `AGENTS.md` file.
#' @export
#'
#' @examples
#' \dontrun{
#' # Run once in your mizer project to set up AI agent support
#' setup_mizer_agent()
#'
#' # In a mizer extension package, add the package development tools and
#' # connect the session automatically on startup
#' setup_mizer_agent(pkg_dev = TRUE, rprofile = TRUE)
#'
#' # A read-only connection: documentation and inspection, but no execution
#' setup_mizer_agent(run_r = FALSE)
#' }
setup_mizer_agent <- function(path = ".", overwrite = FALSE,
                              r_session = TRUE, run_r = TRUE,
                              pkg_dev = FALSE, rprofile = FALSE) {
    agents_src    <- system.file("AGENTS.md",     package = "mizerAgents")
    llms_src      <- system.file("llms.txt",      package = "mizerAgents")
    llms_full_src <- system.file("llms-full.txt", package = "mizerAgents")
    skills_src    <- system.file("skills",        package = "mizerAgents")
    mizer_dest    <- normalizePath(file.path(path, "MIZER-AGENTS.md"), mustWork = FALSE)
    agents_dest   <- normalizePath(file.path(path, "AGENTS.md"),       mustWork = FALSE)

    mizer_section <- paste(readLines(agents_src, warn = FALSE), collapse = "\n")

    # Add a "task skills" index to the always-loaded reference card, generated
    # from the bundled skills' own frontmatter. Claude Code discovers
    # `.claude/skills/` natively; every other agent does not, so this index is
    # how they learn which skills exist and when to read them. Only the index
    # (names + descriptions + path) is added here; the skill bodies stay on disk
    # and are read on demand, mirroring Claude Code's lazy loading.
    if (nzchar(skills_src) && dir.exists(skills_src)) {
        skill_dirs <- sort(list.dirs(skills_src, recursive = FALSE))
        index_lines <- vapply(skill_dirs, function(d) {
            sprintf("- **`%s`** — %s",
                    basename(d), .skill_description(file.path(d, "SKILL.md")))
        }, character(1))
        mizer_section <- paste0(
            mizer_section,
            "\n\n## Task skills (read on demand)\n\n",
            "Step-by-step guides for common mizer tasks are installed under ",
            "`.claude/skills/<name>/SKILL.md`. Claude Code loads them ",
            "automatically; other agents should **read the matching file before ",
            "starting** such a task rather than working from memory. Triggers:\n\n",
            paste(index_lines, collapse = "\n"), "\n"
        )
    }

    # Tell the agent how to use the live session, before pointing it at the
    # static documentation below: help pages from the installed mizer are more
    # trustworthy than the bundled snapshots, which were taken at whatever
    # version this package was last built against.
    if (isTRUE(r_session)) {
        mizer_section <- paste0(mizer_section,
                                .r_session_section(run_r, pkg_dev))
    }

    # Append local paths to both documentation files
    mizer_section <- paste0(
        mizer_section,
        "\n\n## API documentation (local copies)\n\n",
        "Concise overview of the mizer API (start here):\n",
        llms_src, "\n\n",
        if (nzchar(llms_full_src)) {
            paste0(
                "Full API documentation with complete details on every function:\n",
                llms_full_src, "\n",
                "Grep or search this file for specific function names - do not read the whole file.\n"
            )
        } else {
            "Full API documentation: see https://sizespectrum.org/mizer/reference/\n"
        }
    )

    # Always write/overwrite the package-managed MIZER-AGENTS.md file
    writeLines(mizer_section, mizer_dest)
    message("Created ", mizer_dest)

    # Handle AGENTS.md. Unlike MIZER-AGENTS.md this file belongs to the user, so
    # only the marked block is package-managed: it is refreshed in place on every
    # run, wherever in the file it sits, and the rest is left untouched.
    shim <- c(.shim_begin, .shim_note, .shim_end)
    if (file.exists(agents_dest) && !overwrite) {
        existing <- readLines(agents_dest, warn = FALSE)
        range <- .shim_range(existing)
        if (is.null(range)) {
            updated <- c(shim, "", existing)
            action <- "Prepended @MIZER-AGENTS.md shim to existing "
        } else {
            updated <- c(existing[seq_len(range[1] - 1)], shim,
                         existing[-seq_len(range[2])])
            action <- "Refreshed the mizer block in "
        }
        # Leave the file alone when nothing would change, so that re-running
        # setup does not dirty a tracked file or bump its mtime.
        if (!identical(updated, existing)) {
            writeLines(updated, agents_dest)
            message(action, agents_dest)
        }
    } else {
        writeLines(shim, agents_dest)
        message("Created ", agents_dest, " with shim pointing to MIZER-AGENTS.md")
    }

    # Create agent-specific shim files that forward to AGENTS.md.
    # Only written if the file does not already exist (may contain custom content).
    shims <- c("CLAUDE.md", "GEMINI.md")
    for (shim in shims) {
        shim_dest <- normalizePath(file.path(path, shim), mustWork = FALSE)
        if (!file.exists(shim_dest)) {
            writeLines("@AGENTS.md", shim_dest)
            message("Created ", shim_dest)
        }
    }

    # Deploy the bundled Claude skills into `.claude/skills/`. Each skill is a
    # sub-directory containing a `SKILL.md` file. These are package-managed, so
    # they are always refreshed (like `MIZER-AGENTS.md`) to stay up to date.
    if (nzchar(skills_src) && dir.exists(skills_src)) {
        skills_dest <- normalizePath(file.path(path, ".claude", "skills"),
                                     mustWork = FALSE)
        dir.create(skills_dest, recursive = TRUE, showWarnings = FALSE)
        skill_dirs <- list.dirs(skills_src, recursive = FALSE)
        for (skill_dir in skill_dirs) {
            dest <- file.path(skills_dest, basename(skill_dir))
            if (dir.exists(dest)) unlink(dest, recursive = TRUE)
            file.copy(skill_dir, skills_dest, recursive = TRUE)
            message("Installed skill: ", basename(skill_dir))
        }
    }

    # Configure the MCP server that connects the agent to the user's R session.
    # Like the block in `AGENTS.md`, only our own entry is managed; anything
    # else in `.mcp.json` belongs to the user.
    if (isTRUE(r_session)) {
        mcp_dest <- normalizePath(file.path(path, ".mcp.json"), mustWork = FALSE)
        if (.write_mcp_json(mcp_dest, run_r, pkg_dev)) {
            message("Configured the ", .mcp_server_name, " MCP server in ", mcp_dest)
        }
        if (isTRUE(rprofile)) {
            rprofile_dest <- normalizePath(file.path(path, ".Rprofile"),
                                           mustWork = FALSE)
            if (.write_rprofile(rprofile_dest)) {
                message("Added btw::btw_mcp_session() to ", rprofile_dest)
            }
        }
    }

    message(
        "\nMizer API documentation for AI agents:",
        "\n  Overview:  ", llms_src,
        if (nzchar(llms_full_src)) paste0("\n  Full docs: ", llms_full_src) else "",
        if (nzchar(skills_src) && dir.exists(skills_src)) {
            "\n  Skills:    .claude/skills/ (loaded automatically by Claude Code)"
        } else "",
        if (isTRUE(r_session)) {
            .r_session_message(run_r, rprofile, pkg_dev)
        } else "",
        "\n\nStart your AI coding agent from the terminal, e.g.:\n",
        "  claude    (Claude Code)\n",
        "  codex     (Codex CLI)\n",
        "  gemini    (Gemini CLI)\n",
        "  agy       (Antigravity CLI)\n",
        "  copilot   (GitHub Copilot CLI)"
    )

    invisible(agents_dest)
}
